name: CI \ CD

on:
    push:
        branches:
            - main

jobs:
    pipelines:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: Dependencies
              run: npm i
            
            - name: Semver
              run: npm i -g semver
            
            - name: Create a new tag if it doesn't exist
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                if [ -z "$(git tag --list)" ]; then
                    git config --global user.name 'github-actions'
                    git config --global user.email 'github-actions@github.com'
                    git tag -a v0.0.0 -m "Initial release"
                    git push origin v0.0.0
                else
                    echo "Tag v0.0.0 já existe - nenhuma ação necessária."
                fi